"""create books table

Revision ID: 0ca7ba515b8e
Revises: caca5a3cc399
Create Date: 2022-02-13 16:19:12.282616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca7ba515b8e'
down_revision = 'caca5a3cc399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_books', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_books')
    # ### end Alembic commands ###
